### ISSUE TITLE
core.js:4117 ERROR TypeError: Constructor cannot be invoked without 'new'

### ISSUE THREAD

**Issue by st-clair-clarke** [fasttime/Polytype#9] opened 2020-05-30 04:36 UTC
Hi,
I have created a simple angular-9 component and attempt to use polytype to extend a typescript Utils class. 

I am using the following packages:
- "@angular/cli": "^9.1.7"
- "typescript": "3.8.3"
- "polytype": "^0.9.4",

```
import {  Component,  OnInit,} from '@angular/core'
import { NgControl } from '@angular/forms'
import { classes } from 'polytype'

export class Utils {
//  constructor() {} - does not work either if uncommented
  
  onFocusInShowPendingValidationStatus( validationStatus: string, evernt?: Event ): string {
    return validationStatus = 'pending'
  }
  
  onFocusOutValidationStatus( validationStatus: string, control: NgControl, event?: Event ): string {
    return validationStatus = control.valid ? 'valid' : 'invalid'
  }
  
  onValueChangedValidationStatus( validationStatus: string, control: NgControl, event? ): string {
    return validationStatus = control.valid ? 'valid' : 'invalid'
  }
}

@Component(
    {
      selector: 'pim-poly-types',
      template: `
        <p>
          poly-types works!
        </p>
      `,
      styles: [],
    } )
export class PolyTypesComponent extends classes( Utils ) implements OnInit {
  
  constructor() {super() }
  
  ngOnInit(): void {
  }
}

```

However, I am consistently getting the following error that prevents the app from running. The app does compile though.

`
core.js:4117 ERROR TypeError: Constructor cannot be invoked without 'new'
    at Object.apply (polytype.mjs:43)
    at new PolyTypesComponent (poly-types.component.ts:36)
    at NodeInjectorFactory.PolyTypesComponent_Factory [as factory] (poly-types.component.ts:39)
    at getNodeInjectable (core.js:3956)
    at instantiateAllDirectives (core.js:8407)
    at createDirectivesInstances (core.js:7774)
    at ɵɵelementStart (core.js:14518)
    at Module.ɵɵelement (core.js:14569)
    at LoginFormComponent_Template (login-form.component.html:85)
    at executeTemplate (core.js:7747)
defaultErrorLogger @ core.js:4117
push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ErrorHandler.handleError @ core.js:4165
(anonymous) @ core.js:29098
push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
push.../../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NgZone.runOutsideAngular @ core.js:28074
push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ApplicationRef.tick @ core.js:29098
(anonymous) @ core.js:28954
push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
onInvoke @ core.js:28134
push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:385
push.../../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NgZone.run @ core.js:28029
next @ core.js:28953
schedulerFn @ core.js:25506
push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push.../../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.EventEmitter.emit @ core.js:25488
checkStable @ core.js:28084
onHasTask @ core.js:28148
push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:441
push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:462
push.../../node_modules/zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:284
push.../../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:601
push.../../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:507
invokeTask @ zone.js:1671
globalZoneAwareCallback @ zone.js:1697
core.js:4117 ERROR Error: Uncaught (in promise): TypeError: Constructor cannot be invoked without 'new'
TypeError: Constructor cannot be invoked without 'new'
    at Object.apply (polytype.mjs:43)
    at new PolyTypesComponent (poly-types.component.ts:36)
    at NodeInjectorFactory.PolyTypesComponent_Factory [as factory] (poly-types.component.ts:39)
    at getNodeInjectable (core.js:3956)
    at instantiateAllDirectives (core.js:8407)
    at createDirectivesInstances (core.js:7774)
    at ɵɵelementStart (core.js:14518)
    at Module.ɵɵelement (core.js:14569)
    at LoginFormComponent_Template (login-form.component.html:85)
    at executeTemplate (core.js:7747)
    at resolvePromise (zone.js:832)
    at resolvePromise (zone.js:784)
    at zone.js:894
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:28122)
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push.../../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push.../../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:507)
    at invokeTask (zone.js:1671)
defaultErrorLogger @ core.js:4117
push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ErrorHandler.handleError @ core.js:4165
next @ core.js:28692
schedulerFn @ core.js:25506
push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push.../../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.EventEmitter.emit @ core.js:25488
(anonymous) @ core.js:28157
push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
push.../../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NgZone.runOutsideAngular @ core.js:28074
onHandleError @ core.js:28157
push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:390
push.../../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:157
_loop_1 @ zone.js:701
api.microtaskDrainDone @ zone.js:708
drainMicroTaskQueue @ zone.js:608
push.../../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:507
invokeTask @ zone.js:1671
globalZoneAwareCallback @ zone.js:1697
`

**Comment by fasttime** [comment] 2020-05-30 14:42
Thanks for the report. You may be able to solve this by setting the `target` compiler option to "ES2015" or preferably "ES2020" in your `tsconfig.json`. Newer versions of `@angular/cli` have this set by default when a project is created with `ng new`.

```
{
  "compilerOptions": {
    ...
    "target": "es2015",
    ...
  }
}
```

Without that setting TypeScript will transpile Polytype to ES3, which doesn't work well for a number of reasons. Granted, the error message could be better.

**Comment by st-clair-clarke** [comment] 2020-05-30 15:24
I was using es5. I have changed it to es2020 but that caused other issues. I made both the target and the lib in tsconfig the same - es2017- and everything seems fine now. Thanks

**Comment by st-clair-clarke** [comment] 2020-05-30 18:29
Although the app runs with the above tsconfig specs, it will not build - it only builds with 'target': es5 - but this then is not compatible with your package. I am in a bind because of these two things. The failure to build with the above specs is not due to your package - it seems to be a more generalised problem with angular. If you find a solution please let me know, because this will also impact the use of your package.

**Comment by fasttime** [comment] 2020-05-30 22:42
Actually Angular 9 should be fine with any JS target version, but you may need to change other settings, too.

It is also possible that some dependencies involved in the build process don't support ES6.
If you can spot which one they are, maybe from some error message, you may be able to update or replace them.

Another option is to import/include Polytype as an external dependency rather than have it bundled with the rest of the code. If you can do it you could keep targeting ES5 in TypeScript and copy the Polytype package folder unchanged into your dist folder.

Finally, if ES5 is required for compatibility with old browsers, then Polytype may not be the right tool for you. In this case [mixins](https://www.typescriptlang.org/docs/handbook/mixins.html) may be a more appropriate choice.

This is very generic advice but it's all I can think of without more detailed info, and porting Polytype to ES5 is not an option. Please, let me know if you manage to solve your problem in a way or another.

**Comment by fasttime** [comment] 2020-06-02 06:32
The problem is that the call to `super()` gets transpiled by TypeScript into `Object.apply(...)`. But ES6 constructors require constructor semantics to be invoked (`new ...`).

If you know the arguments passed to every base constructor in advance, you can use a wrapper around the call to `classes` to enforce a `new` expression. In your example:

```ts

const PolyTypesComponentBase = classes(Utils);
const WrapPolyTypesComponentBase =
function () { return new PolyTypesComponentBase; } as unknown as typeof PolyTypesComponentBase;

...
export class PolyTypesComponent extends WrapPolyTypesComponentBase implements OnInit {
```

I'd call this a kind of a transpiler hack. It works as long as no additional functionality is needed.

**Comment by st-clair-clarke** [comment] 2020-06-03 04:32
Tried it with the following tsconfig parms but it didn't work.

"target": "es6",
"module": "esnext",
"typeRoots": ["node_modules/@types"],
"lib": ["es2015", "dom"],

**Comment by fasttime** [comment] 2020-06-03 05:59
Does it work with your old config with `"target": "es5"`?

**Comment by fasttime** [comment] 2020-07-12 10:14
Polytype 0.10 will fail to load if the module is transpiled to ES5 or ES3 code, and will throw an error with a message describing the problem instead. I'm going to close this issue by now. Let me know if you need more help.

**Closed by fasttime** 2020-07-12 10:14 UTC
Labels: enhancement
